### ISSUE TITLE
🐛  Prevent duplication by tracking Tables

### ISSUE THREAD

**Issue by yezz123** [yezz123/ormdantic#33]

**Comment by WickedSs** [comment]
You mean the same exact data being inserted many times in a table?

**Comment by yezz123** [comment]
> You mean the same exact data being inserted many times in a table?

Yes, it related almost to m2m relations a lot of times, as I found by reading on it :

- you need to store repetitive data in this table that would be an intersection table in M2M, so you lose storage space for these additional “instances”.

- some of your indexes that could be unique in M2M design may be only non-unique now.

- whenever these repeated data are to be updated you must take care of updating their repeated instances in other records of the table.

- whenever you insert some data you may need to multiply records M times (this M comes from this reduced side of the M2M relation).
