### ISSUE TITLE
Enhancement: Support Python 3.8 & 3.9

### ISSUE THREAD

**Issue by yezz123** [yezz123/ormdantic#7]

**Comment by iron3oxide** [comment]
I don't understand the "good first issue" label here: do you want new contributors to have a look at this or do you plan on doing it yourself? There is not enough information here for people who are not accustomed to the code base and you are still assigned to this issue. 

The "good first issue" label is supposed to point potential contributors to an easy task they could start with (It took me until about two months ago to understand that, so I don't mean to berate you, just asking).

**Comment by yezz123** [comment]
> I don't understand the "good first issue" label here: do you want new contributors to have a look at this or do you plan on doing it yourself? There is not enough information here for people who are not accustomed to the code base and you are still assigned to this issue.
> 
> The "good first issue" label is supposed to point potential contributors to an easy task they could start with (It took me until about two months ago to understand that, so I don't mean to berate you, just asking).

Well, I refer to this `good first issue` label as a thing that should be worked on in the upcoming days and for the next releases, and I use it sometimes for some good questions.

But as you said its also to point potential contributors to an easy task they could start with and I totally agree with that, guess I should create some labels to make everything more clear
